---
  swappiness:
    file: /proc/sys/vm/swappiness
    min: 0
    max: 100
    # float: yes # enable this to allow it to be non-int
  somaxconn:
    file: /proc/sys/net/core/somaxconn
    min: 128
    max: 4096
  numa_balancing:
    file: /proc/sys/kernel/numa_balancing
    min: 0
    max: 1
  dirty_ratio:
    file: /proc/sys/vm/dirty_ratio
    min: 0
    max: 100
  dirty_background_ratio:
    file: /proc/sys/vm/dirty_background_ratio
    min: 0
    max: 100
  dirty_expire_centisecs:
    file: /proc/sys/vm/dirty_expire_centisecs
    min: 100
    max: 20000
  netdev_max_backlog:
    file: /proc/sys/net/core/netdev_max_backlog
    min: 100
    max: 5000
  rmem_max:
    file: /proc/sys/net/core/rmem_max
    min: 256
    max: 16777216
  wmem_max:
    file: /proc/sys/net/core/wmem_max
    min: 256
    max: 16777216
  tcp_max_syn_backlog:
    file: /proc/sys/net/ipv4/tcp_max_syn_backlog
    min: 128
    max: 10240
  tcp_slow_start_after_idle:
    file: /proc/sys/net/ipv4/tcp_slow_start_after_idle
    min: 0
    max: 1
  tcp_tw_reuse:
    file: /proc/sys/net/ipv4/tcp_tw_reuse
    min: 0
    max: 1
  tcp_abort_on_overflow:
    file: /proc/sys/net/ipv4/tcp_abort_on_overflow
    min: 0
    max: 1
  rq_affinity:
    file: /sys/block/sda/queue/rq_affinity
    min: 1
    max: 2
  scheduler:
    file: /sys/block/sda/queue/scheduler
    range:
      - noop
      - deadline
      - cfq
    restore_fallback: deadline
  nr_requests:
    file: /sys/block/sda/queue/nr_requests
    min: 16
    max: 1024
  read_ahead_kb:
    file: /sys/block/sda/queue/read_ahead_kb
    min: 0
    max: 512
  atime:
    complex: yes
    cmd_before: "mount -o "
    cmd_after: ",remount /"
    range:
      - noatime
      - strictatime
      - relatime
    default: relatime
